apiVersion: v1
kind: Service
metadata:
  name: custom-cowsay-ingress
  namespace: fun
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: / 
        pathType: Prefix
        port:
          number: 80

