apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custom-cowsay-ingress
  namespace: fun
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: custom-cowsay-service
            port:
              number: 80

